# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@3
# workflows:
#   test:
#     jobs:
#       - cypress/run:
#           install-browsers: true
#           cypress-command: 'npx cypress run --browser chrome'

version: 2.1
jobs:
  workspace:
    docker:
      - image: cimg/base:2022.05
    steps:
      - attach_workspace:
          at: /workspace

orbs:
  cypress: cypress-io/cypress@3
workflows:
  test:
    jobs:
      - workspace
      - cypress/run:
          install-browsers: true
          cypress-command: 'npx cypress run --browser chrome'
      - persist_to_workspace:
          root: cypress/screenshots/
          paths:
            - "**"
          name: Screenshots
      - persist_to_workspace:
          root: cypress/videos/
          paths:
            - "**"
          name: Videos




