# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@3
# workflows:
#   test:
#     jobs:
#       - cypress/run:
#           install-browsers: true
#           cypress-command: 'npx cypress run --browser chrome'

version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  test:
    jobs:
      - cypress/run:
          install-browsers: true
          cypress-command: 'npx cypress run --browser chrome'
      - store_artifacts:
          path: cypress/screenshots/
          destination: screenshots/
      - store_artifacts:
          path: cypress/videos/
          destination: videos/





