version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist/
  store_artifacts:
    docker:
      - image: circleci/node:14
    steps:
      - attach_workspace:
          at: .
      - store_artifacts:
          path: dist/
orbs:
  cypress: cypress-io/cypress@3
workflows:
  test:
    jobs:
      - cypress/run:
          install-browsers: true
          cypress-command: 'npx cypress run --browser chrome'
