# version: 2.1

# orbs:
#   cypress: cypress-io/cypress@3
# workflows:
#   test:
#     jobs:
#       - cypress/run:
#           install-browsers: true
#           cypress-command: 'npx cypress run --browser chrome'
version: 2.1
orbs:
  cypress: cypress-io/cypress@3

workflows:
  test:
    jobs:
      - cypress-run

jobs:
  cypress-run:
    executor:
      name: cypress/default
      image: cypress/base:14.15.0
    steps:
      - checkout
      - cypress/install
      - run:
          command: npx cypress run --record --parallel
      - store_artifacts:
          path: cypress/screenshots
          destination: screenshots


