# version: 2.1

# orbs:
#   cypress: cypress-io/cypress@3
# workflows:
#   test:
#     jobs:
#       - cypress/run:
#           install-browsers: true
#           cypress-command: 'npx cypress run --browser chrome'

version: 2.1
orbs:
  cypress: cypress-io/cypress@3

workflows:
  test:
    jobs:
      - cypress-run:
          node-version: 14.15.0

jobs:
  cypress-run:
    executor: cypress/default
    steps:
      - checkout
      - cypress/install
      - cypress/run:
          record: true
          parallel: true
      - store_artifacts:
          path: cypress/screenshots
          destination: screenshots
    working_directory: ~/project
    environment:
      CYPRESS_CACHE_FOLDER: /home/circleci/.cache/Cypress

