# version: 2.1

# orbs:
#   cypress: cypress-io/cypress@3
# workflows:
#   test:
#     jobs:
#       - cypress/run:
#           install-browsers: true
#           cypress-command: 'npx cypress run --browser chrome'

version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Run tests
          command: npx cypress run
      - store_artifacts:
          path: reports/

workflows:
  version: 2
  build-and-test:
    jobs:
      - test
