# version: 2.1

# orbs:
#   cypress: cypress-io/cypress@3
# workflows:
#   test:
#     jobs:
#       - cypress/run:
#           install-browsers: true
#           cypress-command: 'npx cypress run --browser chrome'
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.0.0

workflows:
  test:
    jobs:
      - cypress-run

jobs:
  cypress-run:
    executor:
      name: cypress/base-10
    steps:
      - checkout
      - cypress/install:
          node-version: 14.17.0
          yarn: true
      - cypress/run:
          command: npx cypress run --record --parallel
      - store_artifacts:
          path: cypress/screenshots
          destination: screenshots





