# version: 2.1

# orbs:
#   cypress: cypress-io/cypress@3
# workflows:
#   test:
#     jobs:
#       - cypress/run:
#           install-browsers: true
#           cypress-command: 'npx cypress run --browser chrome'
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.0.0

workflows:
  test:
    jobs:
      - cypress-run

jobs:
  cypress-run:
    executor:
      name: cypress/default
      tag: 0.1.4
    steps:
      - checkout
      - cypress/install
      - cypress/run:
          record: true
          parallel: true
      - store_artifacts:
          path: cypress/screenshots
          destination: screenshots



