version: 2.1
orbs:
  cypress: cypress-io/cypress@3

workflows:
  test:
    jobs:
      - cypress-run:
          install-browsers: true
          cypress-command: 'npx cypress run --browser chrome'

jobs:
  cypress-run:
    executor: cypress/default
    steps:
      - checkout
      - cypress/install
      - run:
          name: Run Cypress tests
          command: |
            npx cypress run --browser chrome
      - store_artifacts:
          path: cypress/screenshots
          destination: screenshots
